pipeline:
  name: test remote - main 1 - non default branch
  identifier: test_remote_main_1_non_default_branch
  tags: {}
  projectIdentifier: Saran_Test
  orgIdentifier: Saran_Org
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo main-1-2
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
