pipeline:
  name: shell-script
  identifier: shellscript
  tags: {}
  projectIdentifier: saran_test
  orgIdentifier: default
  stages:
    - stage:
        name: s1
        identifier: s1_iden
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: s22
        identifier: s22_iden_1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo fvc
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  allowStageExecutions: true
