pipeline:
  name: 1 node
  identifier: _node
  tags: {}
  projectIdentifier: DAG
  orgIdentifier: Saran_Org
  stages:
    - parallel:
        - stage:
            name: s323
            identifier: s32e
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo hello
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: s32
            identifier: s32
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo sadad
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: sd
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
