pipeline:
  stages:
    - name: snow 1
      id: snow_1
      steps:
        - name: snow 1
          id: snow_1
          deploy:
            uses: serviceNowCreate
            with:
              connector: account.testSomething
              ticket_type: release_task
              create_ticket_options: Fields
              fields:
                - key: active
                  value: true
                - key: work_end
                  value: a
                - key: work_start
                  value: <+input>
                - key: activity_due
                  value: <+input>
                - key: percent_complete
                  value: <+input>
                - key: actual_end_date
                  value: <+input>
              log_level: error
    - name: serial_grp
      id: serial_grp
      group:
        stages:
          - name: S1
            id: S1
            steps:
              - name: parallel_group_737c
                id: parallel_group_737c
                parallel:
                  steps:
                    - name: snow create
                      id: snow_create
                      deploy:
                        uses: serviceNowCreate
                        with:
                          connector: account.testSomething
                          ticket_type: sn_ai_governance_assessment_request
                          create_ticket_options: Fields
                          fields:
                            - key: assigned_to
                              value: <+input>
                            - key: asset
                              value: <+input>
                          log_level: error
                    - name: asd
                      id: asd
                      deploy:
                        uses: k8sPatchStep
                        with:
                          workload: <+input>
                          strategy: <+input>
                          skip_steady_state_check: false
                          steady_state_timeout: 5m
                          describe_resources: false
                          kubeconfig: ${{infra.kube_config_path}}
                          namespace: ${{infra.namespace}}
                          release: ${{infra.releaseName}}
                          patch_timeout: 5m
                          log_level: info
                          is_openshift: false
