pipeline:
  stages:
    - name: snow 1
      id: snow_1
      steps:
        - name: snow 1
          id: snow_1
          deploy:
            uses: serviceNowCreate
            with:
              connector: account.testSomething
              ticket_type: release_task
              create_ticket_options: Fields
              fields:
                - key: active
                  value: true
                - key: work_end
                  value: a
                - key: activity_due
                  value: <+input>
                - key: percent_complete
                  value: "60"
                - key: actual_end_date
                  value: <+input>
              log_level: error
