pipeline:
  stages:
    - name: snow 1
      id: snow_1
      steps:
        - name: snow 1
          id: snow_1
          deploy:
            uses: serviceNowCreate
            with:
              connector: account.testSomething
              ticket_type: release_task
              create_ticket_options: Fields
              fields:
                - key: active
                  value: true
                - key: work_end
                  value: a
                - key: work_start
                  value: <+input>
                - key: activity_due
                  value: <+input>
                - key: percent_complete
                  value: <+input>
                - key: actual_end_date
                  value: <+input>
              log_level: error
    - name: serial_grp
      id: serial_grp
      group:
        stages:
          - name: S1
            id: S1
            steps:
              - name: snow create
                id: snow_create
                deploy:
                  uses: serviceNowCreate
                  with:
                    connector: account.testSomething
                    ticket_type: asset_task
                    create_ticket_options: Fields
                    fields:
                      - key: active
                        value: <+input>
                      - key: activity_due
                        value: <+input>
                      - key: u_servicenowtest
                        value: true
                    log_level: error
